export const PRODUCTS_FETCH = 'PRODUCT_FETCH';
export const PRODUCTS_DATA = 'PRODUCT_DATA';
export const PRODUCTS_ERROR = 'PRODUCT_ERROR';

export const PRODUCTS_ADD = 'PRODUCT_ADD';
export const PRODUCTS_EDIT = 'PRODUCT_EDIT';
export const PRODUCTS_REMOVE = 'PRODUCT_REMOVE';

export const PRODUCTS_SORT_BY_COUNT = 'PRODUCT_SORT_BY_COUNT';
export const PRODUCTS_SORT_BY_NAME = 'PRODUCT_SORT_BY_NAME';

export const PRODUCTS_ADD_COMMENT = 'PRODUCT_ADD_COMMENT';
export const PRODUCTS_DELETE_COMMENT = 'PRODUCT_DELETE_COMMENT';

export const PRODUCTS_SET_ACTIVE = 'PRODUCT_SET_ACTIVE';
export const PRODUCTS_DELETE_ACTIVE = 'PRODUCT_DELETE_ACTIVE';
